### ISSUE TITLE
Python requirements

### ISSUE THREAD

**Issue by SkalskiP** [Huage001/PaintTransformer#6]
Firstly, I am very impressed with your project. Great work!

## Current behavior

Currently, a potential user of the repository has to install each necessary library separately

## Expected  behavior

The required libraries would be listed in the requirements.txt file and then the necessary python environment could be installed with a single command. 

```console
pip install -r requirements.txt
```

I am happy to contribute and add this change if you see value in it. :)

**Comment by Huage001** [comment]
Hi, you are right and thank you for your kind suggestion. I agree with you that it would be better to provide a requirements.txt. However, we are terribly sorry that the code will be deleted soon due to some force majeure (refer to Latest Update of readme.md). A possible solution is that you can fork this repo firstly to add the change and the code will be re-released after the conference.
