### ISSUE TITLE
Define the script arguments from the console

### ISSUE THREAD

**Issue by SkalskiP** [Huage001/PaintTransformer#7]
Firstly, I am very impressed with your project. Great work!

## Current behavior

Currently, the user has to open the `inference.py` file and manually change the location of the input file and other necessary parameters.

## Expected  behavior

The user can provide the script arguments from the console and does not need to edit the `inference.py` file.

For example:

```console
python inference.py serial=True
```

I am happy to contribute and add this change if you see value in it. :)

**Comment by Huage001** [comment]
Hi, you are right and thank you for your kind suggestion. I agree with you that there should be some arguments instead of the necessity to modify the source code. However, we are terribly sorry that the code will be deleted soon due to some force majeure (refer to Latest Update of readme.md). A possible solution is that you can fork this repo firstly to add the change and the code will be re-released after the conference.
